[

{"textFa":"مراغه"},
{"textFa":"مرند"},
{"textFa":"میانه"},
{"textFa":"خوی"},
{"textFa":"مهاباد"},
{"textFa":"پارس آباد"},
{"textFa":"مشگین شهر"},
{"textFa":"کاشان"},
{"textFa":"کمال شهر"},
{"textFa":"نظرآباد"},
{"textFa":"دهلران"},
{"textFa":"ایوان"},
{"textFa":"بروجن"},
{"textFa":"دزفول"},
{"textFa":"ابهر"},
{"textFa":"طبس"},
{"textFa":"سیرجان"},
{"textFa":"رفسنجان"},
{"textFa":"شیراز"},
{"textFa":"فسا"},
{"textFa":"سقز"},
{"textFa":"آبیک"},
{"textFa":"ایرانشهر"},
{"textFa":"بانه"},
{"textFa":"زابل"},
{"textFa":"چابهار"},
{"textFa":"کیش"},
{"textFa":"شاهرود"},
{"textFa":"دامغان"},
{"textFa":"جوانرود"},
{"textFa":"سنندج"},

]